Repository Team-Vegin/Vegin-iOS, pull requests merged in 2022-05, with the labels that each got.

#83 ✨ [FEAT] 미션 시작/중단 API 연결
  Vegin_iOS/Vegin_iOS.xcodeproj/project.pbxproj
  Vegin_iOS/Vegin_iOS/Global/Protocol/SendDataDelegate.swift
  Vegin_iOS/Vegin_iOS/Network/APIManagers/HomeAPI.swift
  Vegin_iOS/Vegin_iOS/Network/APIModels/Models/Home/MissionStartResModel.swift
  Vegin_iOS/Vegin_iOS/Network/MoyaTarget/HomeService.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/Cell/CharacterBookCVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/Cell/CharacterBookCVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Home/VC/CharacterBookVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/VC/HomeSB.storyboard
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/cheerUp_light.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/cheerUp_light.imageset/cheerUp_light.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/cheerUp_light.imageset/cheerUp_light@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/cheerUp_light.imageset/cheerUp_light@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/delete_light.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/delete_light.imageset/delete_light.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/delete_light.imageset/delete_light@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/delete_light.imageset/delete_light@3x.png
Labels: 📡 Network, 📱 View, 🍎 Feature, 💜 eunju 💜, 🏠 홈탭

#85 ✨ [FEAT] 피드 게시글 수정 API 연결
  Vegin_iOS/Vegin_iOS.xcodeproj/project.pbxproj
  Vegin_iOS/Vegin_iOS/Network/APIManagers/FeedAPI.swift
  Vegin_iOS/Vegin_iOS/Network/APIModels/Models/Public/EditResModel.swift
  Vegin_iOS/Vegin_iOS/Network/MoyaTarget/FeedService.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedMainPostTVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Feed/SB/FeedWriteSB.storyboard
  Vegin_iOS/Vegin_iOS/Screen/Feed/VC/FeedDetailVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/VC/FeedWriteVC.swift
Labels: 📡 Network, 🍎 Feature, 💜 eunju 💜, 📋 피드탭

#86 ✨ [FEAT] 식단 게시글 수정 API 연결 + 자잘한 UI 수정
  Vegin_iOS/Vegin_iOS/Global/Storyboard/Base.lproj/Main.storyboard
  Vegin_iOS/Vegin_iOS/Network/APIManagers/DietAPI.swift
  Vegin_iOS/Vegin_iOS/Network/APIModels/Models/Sign/SignInDataModel.swift
  Vegin_iOS/Vegin_iOS/Network/MoyaTarget/DietService.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedMainEmptyTVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/VC/FeedWriteVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Write/VC/CalendarVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Write/VC/DietDetailVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Write/VC/WriteVC.swift
Labels: 📡 Network, 📱 View, 🍎 Feature, 💜 eunju 💜, ✅ Chore, ✏️ 기록탭, 📋 피드탭

#88 ✅ [CHORE] 캐릭터 도감 뷰 미션 리스트 삽입 및 UI 수정
  Vegin_iOS/Vegin_iOS/Global/PublicData/AppModel/AppContentDataModel.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/Cell/CharacterBookCVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/Cell/CharacterBookCVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Home/VC/CharacterBookVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/VC/FarmVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/VC/HomeSB.storyboard
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/checkButton.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/checkButton.imageset/checkButton.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/checkButton.imageset/checkButton@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/checkButton.imageset/checkButton@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/check_btn.imageset/check_btn.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/check_btn.imageset/check_btn@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/check_btn.imageset/check_btn@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/check_img.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/check_img.imageset/check_img.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/check_img.imageset/check_img@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/check_img.imageset/check_img@3x.png
Labels: 📱 View, 💜 eunju 💜, ✅ Chore, 🏠 홈탭

#90 ✨ [FEAT] 이모지 선택 알럿창 UI 구성
  Vegin_iOS/Vegin_iOS.xcodeproj/project.pbxproj
  Vegin_iOS/Vegin_iOS/Global/New Group/Xib/EmojiAlertVC.xib
  Vegin_iOS/Vegin_iOS/Global/UIComponent/Class/EmojiAlertVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedDetailEmojiTVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedDetailEmojiTVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Feed/VC/FeedDetailVC.swift
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/_fire.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/_fire.imageset/_fire.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/_fire.imageset/_fire@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/_fire.imageset/_fire@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/heart.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/heart.imageset/heart.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/heart.imageset/heart@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/heart.imageset/heart@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/laugh.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/laugh.imageset/laugh.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/laugh.imageset/laugh@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/laugh.imageset/laugh@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/party.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/party.imageset/party.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/party.imageset/party@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/party.imageset/party@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/smile.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/smile.imageset/smile.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/smile.imageset/smile@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/smile.imageset/smile@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/thumbUp.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/thumbUp.imageset/thumbUp.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/thumbUp.imageset/thumbUp@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/FeedImg/thumbUp.imageset/thumbUp@3x.png
Labels: 📱 View, 🍎 Feature, 💜 eunju 💜, 📋 피드탭

#92 ✨ [FEAT] 피드 상세뷰 이모지 리스트 뷰 구성
  Vegin_iOS/Vegin_iOS.xcodeproj/project.pbxproj
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/CVC/EmojiCountCVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/CVC/EmojiCountCVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedDetailEmojiTVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedDetailEmojiTVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Feed/VC/FeedDetailVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/VC/FeedMainVC.swift
Labels: 📱 View, 🍎 Feature, 💜 eunju 💜, 📋 피드탭

#94 ✨ [FEAT] 캐릭터별 미션 현황 리스트 조회 API 연결
  Vegin_iOS/Vegin_iOS.xcodeproj/project.pbxproj
  Vegin_iOS/Vegin_iOS/Global/Class/BaseVC.swift
  Vegin_iOS/Vegin_iOS/Global/Storyboard/Base.lproj/Main.storyboard
  Vegin_iOS/Vegin_iOS/Network/APIManagers/HomeAPI.swift
  Vegin_iOS/Vegin_iOS/Network/APIModels/Models/Home/MissionListResModel.swift
  Vegin_iOS/Vegin_iOS/Network/MoyaTarget/HomeService.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/VC/FarmVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Write/VC/CalendarVC.swift
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/progressBar.imageset/progressBar.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/progressBar.imageset/progressBar@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/progressBar.imageset/progressBar@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/progressBar_empty.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/progressBar_empty.imageset/progressBar_empty.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/progressBar_empty.imageset/progressBar_empty@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/progressBar_empty.imageset/progressBar_empty@3x.png
Labels: 📡 Network, 🍎 Feature, 💜 eunju 💜, 🏠 홈탭

#96 ✅ [CHORE] 캐릭터 도감 뷰 미션현황에 따른 UI 수정
  Vegin_iOS/Vegin_iOS/Global/Protocol/SendDataDelegate.swift
  Vegin_iOS/Vegin_iOS/Global/PublicData/AppModel/AppContentDataModel.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/Cell/CharacterBookCVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/Cell/CharacterBookCVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Home/VC/CharacterBookVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/VC/FarmVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/VC/HomeSB.storyboard
Labels: 📡 Network, 📱 View, 💜 eunju 💜, ✅ Chore, 🏠 홈탭

#98 ✨ [FEAT] 캐릭터 선택하기 API 연결
  Vegin_iOS/Vegin_iOS.xcodeproj/project.pbxproj
  Vegin_iOS/Vegin_iOS/Global/Protocol/SendDataDelegate.swift
  Vegin_iOS/Vegin_iOS/Global/PublicData/AppModel/AppContentDataModel.swift
  Vegin_iOS/Vegin_iOS/Global/Storyboard/Base.lproj/Main.storyboard
  Vegin_iOS/Vegin_iOS/Network/APIManagers/HomeAPI.swift
  Vegin_iOS/Vegin_iOS/Network/APIModels/Models/Home/CharacterSelectResModel.swift
  Vegin_iOS/Vegin_iOS/Network/MoyaTarget/HomeService.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/Cell/CharacterBookCVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/Cell/CharacterBookCVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Home/VC/CharacterBookVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/VC/FarmVC.swift
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/blueberry_bg.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/blueberry_bg.imageset/blueberry_bg.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/blueberry_bg.imageset/blueberry_bg@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/blueberry_bg.imageset/blueberry_bg@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/cabbage_bg.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/cabbage_bg.imageset/cabbage_bg.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/cabbage_bg.imageset/cabbage_bg@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/cabbage_bg.imageset/cabbage_bg@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/carrot_bg.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/carrot_bg.imageset/carrot_bg.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/carrot_bg.imageset/carrot_bg@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/carrot_bg.imageset/carrot_bg@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/corn_bg.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/corn_bg.imageset/corn_bg.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/corn_bg.imageset/corn_bg@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/corn_bg.imageset/corn_bg@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/onion_bg.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/onion_bg.imageset/onion_bg.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/onion_bg.imageset/onion_bg@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/onion_bg.imageset/onion_bg@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/pumpkin_bg.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/pumpkin_bg.imageset/pumpkin_bg.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/pumpkin_bg.imageset/pumpkin_bg@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/pumpkin_bg.imageset/pumpkin_bg@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/springOnion_bg.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/springOnion_bg.imageset/springOnion_bg.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/springOnion_bg.imageset/springOnion_bg@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/springOnion_bg.imageset/springOnion_bg@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/strawberry_bg.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/strawberry_bg.imageset/strawberry_bg.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/strawberry_bg.imageset/strawberry_bg@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/strawberry_bg.imageset/strawberry_bg@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/watermelon_bg.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/watermelon_bg.imageset/watermelon_bg.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/watermelon_bg.imageset/watermelon_bg@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Characters/watermelon_bg.imageset/watermelon_bg@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Icons/_smile.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Icons/_smile.imageset/_smile.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Icons/_smile.imageset/_smile@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Icons/_smile.imageset/_smile@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Icons/left.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Icons/left.imageset/left.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Icons/left.imageset/left@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Icons/left.imageset/left@3x.png
Labels: 📡 Network, 🍎 Feature, 💜 eunju 💜, 🏠 홈탭

#100 ✨[FEAT] : 스플래시 및 온보딩 UI 구현
  Vegin_iOS/Vegin_iOS.xcodeproj/project.pbxproj
  Vegin_iOS/Vegin_iOS/Global/PublicData/AppModel/AppContentDataModel.swift
  Vegin_iOS/Vegin_iOS/Global/Storyboard/Base.lproj/LaunchScreen.storyboard
  Vegin_iOS/Vegin_iOS/Screen/Onboarding/Cell/OnboardingCVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Onboarding/Cell/OnboardingCVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Onboarding/SB/OnboardingSB.storyboard
  Vegin_iOS/Vegin_iOS/Screen/Onboarding/VC/OnboardingVC.swift
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding1.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding1.imageset/Onboarding1.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding1.imageset/Onboarding1@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding1.imageset/Onboarding1@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding2.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding2.imageset/Onboarding2.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding2.imageset/Onboarding2@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding2.imageset/Onboarding2@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding3.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding3.imageset/Onboarding3.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding3.imageset/Onboarding3@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding3.imageset/Onboarding3@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding4.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding4.imageset/Onboarding4.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding4.imageset/Onboarding4@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Onboarding/Onboarding4.imageset/Onboarding4@3x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Splash_img.imageset/Contents.json
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Splash_img.imageset/Splash_img.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Splash_img.imageset/Splash_img@2x.png
  Vegin_iOS/Vegin_iOS/Support/Assets.xcassets/Splash_img.imageset/Splash_img@3x.png
  Vegin_iOS/Vegin_iOS/Support/SceneDelegate.swift
  Vegin_iOS/Vegin_iOS/Support/splash.png
Labels: 📱 View, 🍎 Feature, 💙 Taeeun 💙

#102 ✨ [FEAT] 홈 화면 캐릭터 대사 랜덤 설정 구현
  Vegin_iOS/Vegin_iOS.xcodeproj/project.pbxproj
  Vegin_iOS/Vegin_iOS/Global/Struct/CharacterLines.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/VC/FarmVC.swift
Labels: 📱 View, 🍎 Feature, 💜 eunju 💜, 🏠 홈탭

#103 ✨ [FEAT] 앱 설치 시 온보딩 화면 최초 한번만 보이도록 설정
  Vegin_iOS/Vegin_iOS.xcodeproj/project.pbxproj
  Vegin_iOS/Vegin_iOS/Global/Extension/UserDefaults+.swift
  Vegin_iOS/Vegin_iOS/Screen/Onboarding/Cell/OnboardingCVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Onboarding/SB/OnboardingSB.storyboard
  Vegin_iOS/Vegin_iOS/Screen/SignIn/VC/SignInVC.swift
  Vegin_iOS/Vegin_iOS/Support/SceneDelegate.swift
  Vegin_iOS/Vegin_iOS/Support/splash.png
Labels: 📱 View, 🍎 Feature, 💜 eunju 💜, ✅ Chore

#109 ✨ [FEAT] 인스타그램 스토리 공유 기능 구현
  Vegin_iOS/Vegin_iOS/Global/Storyboard/Base.lproj/Main.storyboard
  Vegin_iOS/Vegin_iOS/Screen/Home/VC/FarmVC.swift
  Vegin_iOS/Vegin_iOS/Support/Info.plist
Labels: 🍎 Feature, 💜 eunju 💜, 🏠 홈탭

#110 ✨ [FEAT] 마이페이지 API 연결
  Vegin_iOS/Podfile
  Vegin_iOS/Podfile.lock
  Vegin_iOS/Pods/Manifest.lock
  Vegin_iOS/Pods/Pods.xcodeproj/project.pbxproj
  Vegin_iOS/Pods/Pods.xcodeproj/xcuserdata/eunju.xcuserdatad/xcschemes/xcschememanagement.plist
  Vegin_iOS/Pods/Target Support Files/Pods-Vegin_iOS/Pods-Vegin_iOS-acknowledgements.markdown
  Vegin_iOS/Pods/Target Support Files/Pods-Vegin_iOS/Pods-Vegin_iOS-acknowledgements.plist
  Vegin_iOS/Pods/Target Support Files/Pods-Vegin_iOS/Pods-Vegin_iOS-frameworks-Debug-input-files.xcfilelist
  Vegin_iOS/Pods/Target Support Files/Pods-Vegin_iOS/Pods-Vegin_iOS-frameworks-Debug-output-files.xcfilelist
  Vegin_iOS/Pods/Target Support Files/Pods-Vegin_iOS/Pods-Vegin_iOS-frameworks-Release-input-files.xcfilelist
  Vegin_iOS/Pods/Target Support Files/Pods-Vegin_iOS/Pods-Vegin_iOS-frameworks-Release-output-files.xcfilelist
  Vegin_iOS/Pods/Target Support Files/Pods-Vegin_iOS/Pods-Vegin_iOS-frameworks.sh
  Vegin_iOS/Pods/Target Support Files/Pods-Vegin_iOS/Pods-Vegin_iOS.debug.xcconfig
  Vegin_iOS/Pods/Target Support Files/Pods-Vegin_iOS/Pods-Vegin_iOS.release.xcconfig
  Vegin_iOS/Vegin_iOS.xcodeproj/project.pbxproj
  Vegin_iOS/Vegin_iOS.xcodeproj/xcuserdata/eunju.xcuserdatad/xcschemes/xcschememanagement.plist
  Vegin_iOS/Vegin_iOS/Global/Storyboard/Base.lproj/Main.storyboard
  Vegin_iOS/Vegin_iOS/Network/APIManagers/MyPageAPI.swift
  Vegin_iOS/Vegin_iOS/Network/APIModels/Models/MyPage/MyPageDataModel.swift
  Vegin_iOS/Vegin_iOS/Network/MoyaTarget/MyPageService.swift
  Vegin_iOS/Vegin_iOS/Screen/Home/VC/FarmVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Mypage/VC/MypageVC.swift
Labels: 📡 Network, 📱 View, 🍎 Feature, 💜 eunju 💜, 🙋🏻‍♀️ 마이페이지탭

#112 ✨ [FEAT] 이모지 달기 API 연결
  Vegin_iOS/Vegin_iOS.xcodeproj/project.pbxproj
  Vegin_iOS/Vegin_iOS/Global/New Group/Xib/EmojiAlertVC.xib
  Vegin_iOS/Vegin_iOS/Global/Storyboard/Base.lproj/Main.storyboard
  Vegin_iOS/Vegin_iOS/Global/UIComponent/Class/EmojiAlertVC.swift
  Vegin_iOS/Vegin_iOS/Network/APIManagers/FeedAPI.swift
  Vegin_iOS/Vegin_iOS/Network/APIModels/Models/Feed/FeedEmojiResModel.swift
  Vegin_iOS/Vegin_iOS/Network/APIModels/Models/Feed/FeedPostDataModel.swift
  Vegin_iOS/Vegin_iOS/Network/MoyaTarget/FeedService.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/CVC/EmojiCountCVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/CVC/EmojiCountCVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedDetailContentTVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedDetailContentTVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedDetailEmojiTVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedDetailTitleTVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedDetailTitleTVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Feed/SB/FeedDetailSB.storyboard
  Vegin_iOS/Vegin_iOS/Screen/Feed/VC/FeedDetailVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Mypage/VC/MypageVC.swift
Labels: 📡 Network, 📱 View, 🍎 Feature, 💜 eunju 💜, 📋 피드탭

#114 ✨ [FEAT] EmptyView 삽입
  Vegin_iOS/Vegin_iOS.xcodeproj/project.pbxproj
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedDetailContentTVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedDetailContentTVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Feed/VC/FeedDetailVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Write/Cell/TVC/DietListTVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Write/Cell/TVC/EmptyViewTVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Write/Cell/TVC/EmptyViewTVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Write/VC/DietListVC.swift
Labels: 📱 View, 🍎 Feature, 💜 eunju 💜, ✏️ 기록탭

#118 🔨 [FIX] 회원가입 뷰 키보드 처리
  Vegin_iOS/Vegin_iOS/Screen/SignIn/VC/SignInVC.swift
  Vegin_iOS/Vegin_iOS/Screen/SignUp/VC/SignUpVC.swift
Labels: 🐞 Bug, 📱 View, 💜 eunju 💜

#120 ✅ [CHORE] 피드 메인 뷰 카테고리 셀 헤더뷰로 변경
  Vegin_iOS/Vegin_iOS.xcodeproj/project.pbxproj
  Vegin_iOS/Vegin_iOS/Global/Storyboard/Base.lproj/Main.storyboard
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/CVC/CategoryCVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedMainTitleTVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/Cell/TVC/FeedMainTitleTVC.xib
  Vegin_iOS/Vegin_iOS/Screen/Feed/SB/FeedWriteSB.storyboard
  Vegin_iOS/Vegin_iOS/Screen/Feed/VC/FeedMainVC.swift
  Vegin_iOS/Vegin_iOS/Screen/Feed/VC/FeedWriteVC.swift
Labels: 🐞 Bug, 📱 View, 💜 eunju 💜, ✅ Chore, 📋 피드탭
